replicaCount: 1

image:
  tag: "10.11.4"

podLabels:
  app: jellyfin

persistence:
  config:
    enabled: true
  media:
    enabled: true
    type: hostPath
    accessMode: ReadOnlyMany
    hostPath: '/vault/media'

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: homelab.lan/nfs-node
              operator: In
              values:
                - "true"

resources: 
    requests: 
        gpu.intel.com/i915: "1" 
    limits: 
        gpu.intel.com/i915: "1" 

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "infra-cs-bouncer@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "${JELLYFIN_DOMAIN}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "${JELLYFIN_DOMAIN}"
      secretName: jellyfin-cert

volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: jellyfin-backup-pvc

# mounts for container
volumeMounts:
  - name: backup
    mountPath: /config/data/backups
  - name: media
    mountPath: /media/movies
    subPath: movies
    readOnly: true
  - name: media
    mountPath: /media/series
    subPath: series
    readOnly: true
  - name: media
    mountPath: /media/animes
    subPath: animes
    readOnly: true
