
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    discovery.kubernetes "k3s_pods" {
      role = "pod"
    }

    prometheus.scrape "k3s_pods" {
      targets    = discovery.kubernetes.k3s_pods.targets

      scrape_interval = "30s"
    
      relabel_configs {
        source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_scrape"]
        regex         = "true"
        action        = "keep"
      }

      relabel_configs {
        source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_port"]
        target_label  = "__address__"
        replacement   = "$1"
        regex         = "(.+)"
        action        = "replace"
      }
    
      forward_to = [prometheus.remote_write.grafana_local.receiver]
    }


    prometheus.remote_write "grafana_local" {
      endpoint {
          name = "selfhosted-prometheus"
          url  = "http://prometheus-server.monitoring.svc.cluster.local"
      }
    }


    prometheus.remote_write "grafana_cloud" {
      endpoint {
          name = "cloud-prometheus"
          url  = "https://prometheus-prod-58-prod-eu-central-0.grafana.net/api/prom/push"
      
          basic_auth {
            username = "${GRAFANA_USER}"
            password = "${GRAFANA_API_KEY}"
          }
      }
    }
