
image:
  tag: "33.0.1"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "infra-internal-only@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ${NEXTCLOUD_DOMAIN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nextcloud-tls
      hosts:
        - ${NEXTCLOUD_DOMAIN}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: homelab.lan/nfs-node
              operator: In
              values:
                - "true"

nextcloud:
  host: ${NEXTCLOUD_DOMAIN}
  existingSecret:
    enabled: true
    usernameKey: username
    passwordKey: password
    secretName: nc-basic-auth

  extraVolumes:
    - name: nfs-vault
      hostPath:
        path: ${NFS_PATH}
        type: Directory

  extraVolumeMounts:
    - name: nfs-vault
      mountPath: "${NFS_PATH}"

  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'overwrite.cli.url' => 'https://${NEXTCLOUD_DOMAIN}',
        'overwritehost' => '${NEXTCLOUD_DOMAIN}',
        'overwriteprotocol' => 'https',
      );

persistence:
  enabled: true
