apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-backup-pv
  namespace: media
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - proto=tcp
    - nfsvers=4.2
  nfs:
    path: ${NFS_PATH}/backups/audiobookshelf
    server: ${NFS_IP}