apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-backup-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: jellyfin-backup-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi