ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "secure-middleware@kubernetescrd,rate-limit@kubernetescrd,"
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "${GRAFANA_DOMAIN}"
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true

createConfigMap: false

extraConfigmapMounts:
  - name: grafana-provisioning
    mountPath: /etc/grafana/provisioning
    configMap: grafana-provisioning
    readOnly: false

dashboards:
  default:
    traefik:
      gnetId: 4475
      revision: 5
      datasource: Prometheus
    kubernetes:
      gnetId: 15661
      revision: 2
      datasource: Prometheus
    crowdsec-overview:
      url: https://github.com/crowdsecurity/grafana-dashboards/blob/master/dashboards_v5/Crowdsec%20Overview.json
      curlOptions: "-sLf"
    crowdsec-detail-per-machine:
      url: https://github.com/crowdsecurity/grafana-dashboards/blob/master/dashboards_v5/Crowdsec%20Details%20per%20Machine.json
      curlOptions: "-sLf"

admin:
  existingSecret: "basic-auth"
  userKey: username
  passwordKey: password
