apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: books-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi