apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      updateIntervalSeconds: 10
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true
      editable: false
