version: '3.8'

services:
  portainer:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma    
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=network_private"
        - "traefik.http.routers.uptime.middlewares=internal-only@file"
        - "traefik.http.routers.uptime.rule=Host(`${UPTIME_KUMA_DOMAIN}`)"
        - "traefik.http.routers.uptime.entrypoints=websecure"
        - "traefik.http.services.uptime.loadbalancer.server.port=9000"
    # ports:
    #   - ${UPTIME_KUMA_PORT}:9000
    environment:
      TZ: "Europe/Budapest"
    volumes:
      - ${NAS_PATH}/configs/uptime-kuma:/app/data
    networks:
      - network_private

networks:
  network_private:
    external: true
