cluster:
  name: default
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-58-prod-eu-central-0.grafana.net./api/prom/push
    auth:
      type: basic
      username: "2741535"
      password: ${GRAFANA_API_KEY}
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-039.grafana.net./loki/api/v1/push
    auth:
      type: basic
      username: "1366444"
      password: ${GRAFANA_API_KEY}
clusterMetrics:
  enabled: true
  kepler:
    enabled: true
annotationAutodiscovery:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: false
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
